Use permission standard.
ensdomains/blacklist pull request #10
Opened 2018-02-03 21:04 UTC by clesaege

2018-02-03 21:21 UTC, decanus requested changes

2018-02-03 21:21 UTC, decanus commented on contracts/Blacklist.sol
> +    /** @dev Add a node to the blacklist.
There should be a new line where the first comment is on, for all other comments.

2018-02-03 21:27 UTC, decanus requested changes

2018-02-03 21:27 UTC, decanus commented on contracts/BlacklistInterface.sol
> +    function isAllowed(bytes32 node) public view returns (bool);
Let's cut out the descriptions from here, along with the param declaration and only have them in ```Blacklist.sol```

2018-02-04 11:29 UTC, decanus approved these changes

2018-03-06 22:27 UTC, decanus commented
@clesaege you can merge this

2018-03-07 14:28 UTC, clesaege commented
@decanus I can't, I don't have write access.

2018-03-07 14:29 UTC, decanus commented
@clesaege, my bad. I'll merge

2018-03-07 14:29 UTC, merged